config/routes.rb
Rails.application.routes.draw do
	get 				'login', 			    			to: 'sessions#new'
	post 				'login',		    				to: 'sessions#create'
	delete 				'logout', 		        			to: 'sessions#destroy'

	root                                      				'static_pages#index'
	get                 'appointments_coming',              to: 'static_pages#appointments_coming'
	get                 'appointments_today',                to: 'static_pages#appointments_today'

	get 				'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 				'doctors',                          to: 'doctors#index'
	get 				'users',                            to: 'users#index'

	get 				'doctor_login',		           		to: 'sessions#new_doctor'
	post 				'doctor_login',		          		to: 'sessions#create_doctor'
	delete				'doctor_logout', 		    		to: 'sessions#destroy_doctor'

	get					'new_appointment',			    	to: 'appointments#new'
	get                 'welcome',                          to: 'appointments#welcome'
	get                 'list_doctors',                     to: 'appointments#list_doctors'

	get                 'today_appointments',               to: 'doctors#show_today_appointments'
	get                 'coming_appointments',              to: 'doctors#show_coming_appointments'
	get                 'all_appointments',                 to: 'doctors#show_all_appointments'
	resources :gibes, :fields, :doctors, :users, :appointments
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>


  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>


<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
     <div class="copyright float-right">
       &copy;
       A web version,
         Developed by Gibe S. Tirol

    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="sidebar" data-color="purple" data-background-color="white" data-image="../assets/img/sidebar-1.jpg">
	<!--
	  Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

	  Tip 2: you can also add an image using data-image tag
   -->
	<div class="logo"><a href="http://www.creative-tim.com" class="simple-text logo-normal">
		Creative Tim
	</a></div>
	<div class="sidebar-wrapper">
		<ul class="nav">
			<li class="nav-item active  ">
				<%= link_to '<i class="material-icons">dashboard</i><p>Dashboard</p>'.html_safe, root_url, class: 'nav-link', target: "_self" %>
			</li>
			<li class="nav-item ">
				<%= link_to '<i class="material-icons">person</i><p>User Profile</p>'.html_safe, current_user || current_doctor, class: 'nav-link',  target: "_self"%>
			</li>
			<% unless logged_in_doctor? %>
				<li class="nav-item ">
					<%= link_to '<i class="material-icons">group_add</i><p>Users</p>'.html_safe, users_url, class: 'nav-link', target:  "_self" %>
				</li>
				<li class="nav-item">
					<%= link_to  '<i class="material-icons">library_add</i><p>Specialty</p>'.html_safe, fields_url, class: 'nav-link', target: "_self"%>
				</li>
			<% end %>
               <li class="nav-item">
                    <%= link_to '<i class="material-icons">assignment_ind</i><p>Doctors</p>'.html_safe, doctors_path, class: 'nav-link', target: "_self" %>
               </li>
               <% if logged_in_doctor? %>
               <li class="nav-item">
                    <%= link_to '<i class="material-icons">calendar_view_day</i><p>Appointments</p>'.html_safe, all_appointments_path, class: 'nav-link' %>
               </li>
               <li>
                    <%= link_to '<i class="material-icons">calendar_today</i><p>Today''s Appointments</p>'.html_safe, today_appointments_path, class: 'nav-link' %>
               </li>
               <li>
                    <%= link_to '<i class="material-icons">assignment</i><p>Coming Appointments</p>'.html_safe, coming_appointments_path, class: 'nav-link' %>
               </li>
               <% end %>

		</ul>
	</div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
	<div class="container-fluid">

		<button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
			<span class="sr-only">Toggle navigation</span>
			<span class="navbar-toggler-icon icon-bar"></span>
			<span class="navbar-toggler-icon icon-bar"></span>
			<span class="navbar-toggler-icon icon-bar"></span>
		</button>
		<div class="collapse navbar-collapse justify-content-end">
			<ul class="navbar-nav">
		          <% if current_user  %>

				<li class="nav-item dropdown">
					<a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="material-icons">notifications</i>
						<span class="notification">
                                        <%
                                             today = Appointment.where(doa: Time.zone.today).count
                                             coming = Appointment.where('doa > ?', Time.zone.today).count
                                             total = today + coming
                                        %>
                                        <%= total %>

                              </span>
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink" style="width: 220px !important;">
						<%= link_to "Today's #{'appointment'.pluralize(today)} <span class='notification'>#{today}<span>".html_safe, appointments_today_path, class: "dropdown-item" %>
						<%= link_to "Coming #{'appointment'.pluralize(coming)} <span class='notification'>#{coming}<span>".html_safe, appointments_coming_path , class: "dropdown-item" %>
						<%= link_to "Number of #{'staff'.pluralize(User.count)} <span class='notification'>#{User.count}<span>".html_safe, users_path, class: "dropdown-item" %>
						<%= link_to "Number of #{'doctor'.pluralize(Doctor.count)} <span class='notification'>#{Doctor.count}<span>".html_safe, doctors_path, class: "dropdown-item" %>
					</div>
				</li>

                         <% end %>
				<li class="nav-item dropdown">
					<a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="material-icons">person</i>
						<p class="d-lg-none d-md-block">
							Account
						</p>
					</a>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
						<%= link_to "Profile", logged_in? ? current_user : current_doctor, class: "dropdown-item" %>
						<%= link_to "Settings", logged_in? ? edit_user_path(current_user) : edit_doctor_path(current_doctor), class: "dropdown-item" %>
						<div class="dropdown-divider"></div>
						<%= link_to "Log out", logged_in? ? logout_path : doctor_logout_path, method: :delete, class: "dropdown-item" %>
					</div>

				</li>
			</ul>
		</div>
	</div>
</nav>
<!-- End Navbar -->