config/routes.rb
Rails.application.routes.draw do
	get 				'login', 			    			to: 'sessions#new'
	post 				'login',		    				to: 'sessions#create'
	delete 				'logout', 		        			to: 'sessions#destroy'

	root                                      				'static_pages#index'
	get                 'appointments_coming',              to: 'static_pages#appointments_coming'
	get                 'appointments_today',                to: 'static_pages#appointments_today'

	get 				'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 				'doctors',                          to: 'doctors#index'
	get 				'users',                            to: 'users#index'

	get 				'doctor_login',		           		to: 'sessions#new_doctor'
	post 				'doctor_login',		          		to: 'sessions#create_doctor'
	delete				'doctor_logout', 		    		to: 'sessions#destroy_doctor'

	get					'new_appointment',			    	to: 'appointments#new'
	get                 'welcome',                          to: 'appointments#welcome'
	get                 'list_doctors',                     to: 'appointments#list_doctors'

	get                 'today_appointments',               to: 'doctors#show_today_appointments'
	get                 'coming_appointments',              to: 'doctors#show_coming_appointments'
	get                 'all_appointments',                 to: 'doctors#show_all_appointments'
	resources :gibes, :fields, :doctors, :users, :appointments
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	belongs_to :field
	has_many :appointments, dependent: :destroy
	validates :field_id, presence: true
	attr_accessor :remember_token
	before_save {self.email = email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	validates :license, presence: true, length: {maximum: 30}
	validates :contact, presence: true,length: {maximum: 15}
	validates :address, presence: true, length: {maximum: 250}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :email, presence:  true, length: {maximum: 255},
	          format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	
	has_secure_password
	validates :password_digest, presence: true, length: {minimum: 6}

	# Returns the hash digest of the given string.
	def Doctor.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
					BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def Doctor.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = Doctor.new_token
		update_attribute(:remember_digest, Doctor.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest , nil)
	end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	before_action :check_logged_in
	before_action :correct_user, only: [:update, :edit], unless: -> {current_user.nil?}
	before_action :correct_doctor, only: [:update, :edit, :new, :create]

	def index
		#@doctors = Doctor.all
		@doctors = Doctor.order(:name).page(params[:page]).per(15)
	end

	def show
		@doctor = Doctor.find(params[:id])
	end

	def new
		@doctor = Doctor.new

	end

	def create
		@doctor = Doctor.new(doctor_params)
		if @doctor.save
			flash[:success] = "New Doctor account created"
			redirect_to doctors_url
		else
			render 'new'
		end

	end
	def show_all_appointments
		@doctor = Doctor.find(session[:doctor_id])
		@today_appointments = current_doctor.appointments.where(doa: Time.zone.today).limit(10)
		@all_appointments = current_doctor.appointments.where('doa > ?', Time.zone.today).limit(10)
	end

	def show_today_appointments
		@today_appointments = current_doctor.appointments.where(doa: Time.zone.today).page(params[:page]).per(15)

	end

	def show_coming_appointments
		@coming_appointments = current_doctor.appointments.where('doa >?', Time.zone.today).page(params[:page]).per(15)

	end

	def edit
		@doctor = Doctor.find(params[:id])
	end

	def update
		@field = Doctor.find(params[:id])
		if @field.update_attributes(doctor_params)
			flash[:success] = "Doctor Updated"
			redirect_to doctors_url
		else
			render 'edit'
		end
	end

	def destroy
		Doctor.find(params[:id]).delete
		flash[:success] = "Doctor Deleted"
		redirect_to doctors_url
	end

	private
		def doctor_params
			params.require(:doctor).permit(:name, :license, :contact, :address, :email, :password, :password_confirmation, :field_id)
		end


end

app/helpers/doctors_helper.rb
module DoctorsHelper
	def gravatar_for(user, size: 80)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/doctors/_doctor.html.erb
<li>
	<%= doctor.name %>
	<span class="float-sm-right" style= "clear: both;" >
	<%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, doctor, style: "padding-right: 10px", target: "_self", title:"View Doctor" %>
		<% if logged_in? %>
			<% if current_user.admin? %>
				<%= link_to '<i class="material-icons", style="font-size: 24px; color: #da5530">edit</i>'.html_safe, edit_doctor_path(doctor), style: "padding-left: 10px; padding-right: 10px", target: "_self", title:"Edit Doctor" %>
				<%= link_to '<i class="material-icons", style="font-size: 24px; color: #ff0000">delete_forever</i>'.html_safe, doctor, method: :delete, data: {confirm: "Are you sure?"}, target: "_self", title:"Delete Doctor" %>
			<% end  %>
		<% end %>
	</span>
</li>

app/views/doctors/edit.html.erb
<div class="col-md-10">
	<div class="card">
		<div class="card-header card-header-primary">
			<h4 class="card-title">Edit Doctor Profile</h4>
			<p class="card-category">Fill-out completely</p>
		</div>
		<div class="card-body">
			<%= form_with(model: @doctor, local: true) do |f| %>
				<div class="row">
					<div class="col-md-10">
						<%= render 'shared/error_messages', object: f.object %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :name, class: "bmd-label-floating"%>
							<%= f.text_field :name, class: "form-control", autofocus: true %>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :license, class:  "bmd-label-floating" %>
							<%= f.text_field :license, class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :contact, class: "bmd-label-floating" %>
							<%= f.text_field :contact, class: "form-control" %>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :specialty, class: "bmd-label-floating" %>
							<%= f.collection_select :field_id, Field.order(:area), :id, :area, {prompt: "Select Specialty"}, class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<%= f.label :address, class: "bmd-label-floating" %>
							<%= f.text_field :address, class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<%= f.label :email, class: "bmd-label-floating" %>
							<%= f.email_field :email, class: "form-control", autocomplete: true %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<%= f.label :password, class: "bmd-label-floating" %>
							<%= f.password_field :password, class:"form-control" %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<%= f.label :password_confirmation, class: "bmd-label-floating" %>
							<%= f.password_field :password_confirmation, class:"form-control" %>
						</div>
					</div>

				</div>
				<%= f.submit "Update Account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/doctors/index.html.erb
<div class="col-md-10">
     <% unless logged_in_doctor? %>
          <%= link_to "Add Doctor", new_doctor_path, class:"btn btn-primary"%>
     <% end %>
     <div class="card">
          <div class="card-header card-header-primary">
               <h4 class="card-title">List of Doctors</h4>
               <p class="card-category">There are <%= pluralize(Doctor.count, "Doctor") %></p>
          </div>
          <div class="card-body">
               <div class="row">

                    <div class="col-md-12">
                         <ul class="horizontal-display">
                              <%= render @doctors %>
                         </ul>
                         <div class="d-flex justify-content-center">
                              <%= paginate @doctors  %>
                         </div>

                    </div>
               </div>
          </div>
     </div>


</div>

app/views/doctors/new.html.erb
<div class="col-md-10">
	<div class="card">
		<div class="card-header card-header-primary">
			<h4 class="card-title">Doctor Profile</h4>
			<p class="card-category">Fill-out completely</p>
		</div>
		<div class="card-body">
			<%= form_with(model: @doctor, local: true) do |f| %>
				<div class="row">
					<div class="col-md-10">
						<%= render 'shared/error_messages', object: f.object %>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :name, class: "bmd-label-floating"%>
							<%= f.text_field :name, class: "form-control", autofocus: true %>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :license, class:  "bmd-label-floating" %>
							<%= f.text_field :license, class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :contact, class: "bmd-label-floating" %>
							<%= f.text_field :contact, class: "form-control" %>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<%= f.label :specialty, class: "bmd-label-floating" %>
							<%= f.collection_select :field_id, Field.order(:area), :id, :area, {prompt: "Select Specialty"}, class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<%= f.label :address, class: "bmd-label-floating" %>
							<%= f.text_field :address, class: "form-control" %>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<%= f.label :email, class: "bmd-label-floating" %>
							<%= f.email_field :email, class: "form-control", autocomplete: true %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<%= f.label :password, class: "bmd-label-floating" %>
							<%= f.password_field :password, class:"form-control" %>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<%= f.label :password_confirmation, class: "bmd-label-floating" %>
							<%= f.password_field :password_confirmation, class:"form-control" %>
						</div>
					</div>

				</div>
				<%= f.submit "Create Account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/doctors/show.html.erb
<div class="col-md-10">
      <div class="card">
            <div class="card-header card-header-primary">
                  <h4 class="card-title">Doctor Profile</h4>
                  <p class="card-category">Speciality: <%= @doctor.field.area %></p>
            </div>
            <div class="card-body">
                  <div class="row">
                        <div class="col-md-2">
                              <%= gravatar_for @doctor %>
                        </div>
                        <div class="col-md-8">
                              <table class="table">
                                    <tr>
                                          <tr scope="row">
                                                <td colspan="2"><h3><%= @doctor.name %></h3></td>
                                          </tr>
                                          <tr scope="row">
                                                <td><h4>License Number </h4></td>
                                                <td><h4><%= @doctor.license %></h4></td>
                                          </tr>
                                          <tr scope="row">
                                                <td>Email</td>
                                                <td><%= @doctor.email %></td>
                                          </tr>
                                          <tr scope="row">
                                                <td>Contact</td>
                                                <td><%= @doctor.contact %></td>
                                          </tr>
                                          <tr scope="row">
                                                <td>Address</td>
                                                <td><%= @doctor.address %></td>
                                          </tr>
                                    </tbody>
                              </table>
					    <% if correct_user?  %>
                              	<%= link_to "View Appointments", "#", class: "btn btn-primary", target: "_self" %>
					    <% end %>
                        </div>

                  </div>
            </div>
      </div>
</div>

app/views/doctors/show_all_appointments.html.erb
<div class="col-md-12">
     <h2><%= "Hello Doctor " + @doctor.name  %></h2>
     <h5>Date Today: <%= DateTime.now.strftime('%A %B %d, %Y')    %>     </h5>
     <div class="card">
          <div class="card-header card-header-primary">
               <h4 class="card-title">Appointments</h4>
               <p class="card-category">Today and Coming Days</p>
          </div>
          <div class="card-body">
               <div class="row">
                    <div class="col-md-6">
                         <div class="card card-chart">
                              <div class="card-header card-header-success">
                                   <h4>You have <%= pluralize(current_doctor.appointments.where(doa: Time.zone.today).count, "appointment") %> for today</h4>
                              </div>
                              <div class="card-body">
                                   <ul class="horizontal-display" style="padding-left: 10px!important;">
                                        <% @today_appointments.each do |t| %>
                                             <li>
                                                  <%= t.name %>
                                                  <span class="float-sm-right" style= "clear: both;" >
                                                       <%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, appointment_path(t), style: "padding-right: 10px", target: "_self", title:"View Appointment" %>
                                                  </span>
                                             </li>
                                        <% end %>
                                        <% if current_doctor.appointments.where(doa: Time.zone.today).count > 10 %>
                                             <div class="text-center" style="margin-top: 20px">
                                                  <%= link_to "View More", today_appointments_path, class: "btn btn-success" %>
                                             </div>
                                        <% end %>
                                   </ul>
                              </div>
                         </div>
                    </div>
                    <div class="col-md-6">
                         <div class="card card-chart">
                              <div class="card-header card-header-warning">
                                   <h4>You have <%= pluralize(current_doctor.appointments.where('doa > ? ', Time.zone.today).count, "coming appointment") %> </h4>
                              </div>
                              <div class="card-body">
                                   <ul class="horizontal-display">
                                        <% @all_appointments.each do |a| %>
                                             <li>
                                                  <%= a.name %>
                                                  <span class="float-sm-right" style= "clear: both;" >
                                                       <%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, appointment_path(a), style: "padding-right: 10px", target: "_self", title:"View Appointment" %>
                                                  </span>
                                             </li>
                                        <% end %>
                                   </ul>
                                   <% if current_doctor.appointments.where('doa > ? ', Time.zone.today).count > 10 %>
                                        <div class="text-center" style="margin-top: 20px">
                                             <%= link_to "View More", coming_appointments_path, class: "btn btn-warning" %>
                                        </div>
                                   <% end  %>

                              </div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

app/views/doctors/show_coming_appointments.html.erb
<div class="col-md-12">
     <h2><%= "Hello Doctor " + current_doctor.name %></h2>
     <h5>Date Today: <%= DateTime.now.strftime('%A %B %d, %Y') %> </h5>
     <div class="card">
          <div class="card-header card-header-primary">
               <h4 class="card-title">Appointments for today</h4>
               <p>
                    You have <%= pluralize(current_doctor.appointments.where('doa >?', Time.zone.today).count, "appointment")  %> today
               </p>
          </div>
          <div class="card-body">
               <% if @coming_appointments.empty? %>
                    <div class="alert alert-warning">
                         <h3>No Reservation</h3>
                    </div>
               <% else %>
                    <ul class="horizontal-display" style="padding-left: 10px!important;">
                         <% @coming_appointments.each do |a| %>
                              <li>
                                   <%= a.name %>
                                   <span class="float-sm-right" style= "clear: both;" >
                                        <%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, appointment_path(a), style: "padding-right: 10px", target: "_self", title:"View Appointment" %>
                                   </span>
                              </li>
                         <% end %>
                    </ul>
                    <div class="d-flex justify-content-center">
                         <%= paginate @coming_appointments  %>
                    </div>
               <% end %>
          </div>
     </div>
</div>

app/views/doctors/show_today_appointments.html.erb
<div class="col-md-12">
     <h2><%= "Hello Doctor " + current_doctor.name %></h2>
     <h5>Date Today: <%= DateTime.now.strftime('%A %B %d, %Y') %> </h5>
     <div class="card">
          <div class="card-header card-header-primary">
               <h4 class="card-title">Appointments for today</h4>
               <p>
                    You have <%= pluralize(current_doctor.appointments.where(doa: Time.zone.today).count, "appointment")  %> today
               </p>
          </div>
          <div class="card-body">
               <% if @today_appointments.empty? %>
                    <div class="alert alert-warning text-center">
                         <h3>No Reservation</h3>
                    </div>
               <% else %>
                    <ul class="horizontal-display" style="padding-left: 10px!important;">
                         <% @today_appointments.each do |t| %>
                               <li>
                                    <%= t.name %>
                                    <span class="float-sm-right" style= "clear: both;" >
                                        <%= link_to '<i class="material-icons", style="font-size: 24px; color: #2f4858">perm_contact_calendar</i>'.html_safe, appointment_path(t), style: "padding-right: 10px", target: "_self", title:"View Appointment" %>
                                   </span>
                               </li>
                         <% end %>
                    </ul>
                    <div class="d-flex justify-content-center">
                         <%= paginate @today_appointments  %>
                    </div>
               <% end  %>
          </div>
     </div>
</div>