config/routes.rb
Rails.application.routes.draw do
	get 				'login', 			    			to: 'sessions#new'
	post 				'login',		    				to: 'sessions#create'
	delete 				'logout', 		        			to: 'sessions#destroy'

	root                                      				'static_pages#index'
	get                 'appointments_coming',              to: 'static_pages#appointments_coming'
	get                 'appointments_today',                to: 'static_pages#appointments_today'

	get 				'contact',                          to: 'static_pages#contact'
	get					'fields',                           to: 'fields#index'
	get 				'doctors',                          to: 'doctors#index'
	get 				'users',                            to: 'users#index'

	get 				'doctor_login',		           		to: 'sessions#new_doctor'
	post 				'doctor_login',		          		to: 'sessions#create_doctor'
	delete				'doctor_logout', 		    		to: 'sessions#destroy_doctor'

	get					'new_appointment',			    	to: 'appointments#new'
	get                 'welcome',                          to: 'appointments#welcome'
	get                 'list_doctors',                     to: 'appointments#list_doctors'

	get                 'today_appointments',               to: 'doctors#show_today_appointments'
	get                 'coming_appointments',              to: 'doctors#show_coming_appointments'
	get                 'all_appointments',                 to: 'doctors#show_all_appointments'
	resources :gibes, :fields, :doctors, :users, :appointments
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	default_scope  -> { order(doa: :asc) }
	validates :name, presence: true
	validates :address, presence: true
	validates :contact, presence: true
	validates :dob, presence: true
	validates :doa, presence: true
	validates :job, presence: true
	validates :doctor_id, presence: true
	validates :gender, presence: true
	validates :email, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	def show
		@appointment = Appointment.find(params[:id])
	end

	def new
		@appointment = Appointment.new
	end

	def create
		@appointment = Appointment.new(appointment_params)
		if @appointment.save
			flash[:success] = "Your appointment is save";
			render 'show'
		else
			render 'new'
		end
	end

	def welcome
	end

	def list_doctors
		@doctors = Doctor.all
		@fields = Field.order('area').all
	end
	private

		def appointment_params
			params.require(:appointment).permit(:name, :address, :email, :contact, :dob, :doa, :job, :doctor_id, :gender)
		end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/list_doctors.html.erb
<div class="wrapper" style="margin-top: 60px !important;">
     <div class="content">
          <div class="container-fluid">
               <div class="row">
                    <div class="offset-1 col-md-10 offset-1">
                         <div class="card">
                              <div class="card-header card-header-primary">
                                   <h4 class="card-title" style="padding-top: 20px; padding-bottom: 20px;">We have <%= pluralize(Doctor.count, "doctor") %> available</h4>
                              </div>
                              <div class="card-body">
                                   <div class="row">
                                        <div class="col-md-6">
                                             <ul class="horizontal-display" style="padding-left: 10px!important;">
                                                  <% doctors = @doctors.sort_by { | d | d.field.area  } %>
                                                  <% doctors.each do |d| %>
                                                       <li>
                                                            <%= d.name %>
                                                            <span class="float-sm-right" style= "clear: both;" >
                                                                 <%= d.field.area %>
                                                            </span>
                                                       </li>
                                                  <% end %>
                                             </ul>
                                        </div>
                                        <div class="col-md-6">
                                             <ul class="horizontal-display" style="padding-left: 10px!important;">
                                                  <% @fields.each do |f| %>
                                                       <li>
                                                            <h4><%= f.area %>
                                                                 <span class="float-sm-right" style= "clear:both;border-radius: 100px;background-color:#56ae5a;padding:5px;height:40px;width:40px;text-align: center;color: #fff;"  >
                                                                 <%= Doctor.where(field_id: f.id).count %>
                                                            </span>
                                                            </h4>
                                                       </li>
                                                  <% end %>
                                             </ul>
                                        </div>
                                   </div>
                                   <div class="row">
                                        <div class="col-md-12">
                                             <center>
                                                  <%= link_to "Back to Previous", welcome_path, class: "btn btn-primary btn-lg" %>
                                             </center>

                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

app/views/appointments/new.html.erb
<div class="wrapper" style="margin-top: 60px !important;">
     <div class="content">
          <div class="container-fluid">
               <div class="row">
                    <div class="offset-1 col-md-10">
                         <div class="card">
                              <div class="card-header card-header-primary">
                                   <h4 class="card-title">Appointment</h4>
                                   <p class="card-category">Fill-out completely</p>
                              </div>
                              <div class="card-body">
                                   <%= form_for @appointment,  html: {class: 'form-horizontal'} do |f| %>
                                        <div class="row">
                                             <div class="col-md-12">
                                                  <%= render 'shared/error_messages', object: f.object %>
                                             </div>
                                        </div>
                                        <div class="row">
                                             <div class="col-md-4 form-group">
                                                  <%= f.label :name, class: "bmd-label-floating" %>
                                                  <%= f.text_field :name, class: "form-control", autofocus:true %>
                                             </div>
                                             <div class="col-md-4 form-group">
                                                  <%= f.label :address, class: "bmd-label-floating" %>
                                                  <%= f.text_field :address, class: "form-control" %>
                                             </div>
                                             <div class="col-md-4 form-group"?>
                                                  <%= f.label :email, class: "bmd-label-floating" %>
                                                  <%= f.email_field :email, class: "form-control" %>
                                             </div>
                                        </div>
                                        <div class="row">
                                             <div class="col-md-4 form-group ">
                                                  <%= f.label :contact, class: "bmd-label-floating" %>
                                                  <%= f.text_field :contact, class: "form-control" %>
                                             </div>

                                             <div class="col-md-4 form-group">
                                                  <%= f.label :dob, "Date of Birth", class: "bmd-label-floating"  %>

                                                  <%= f.text_field :dob, class: 'form-control change-to-white',id: "dob", placeholder: "Select date", data: {input: 'true'}%>
                                             </div>
                                             <div class="col-md-4 form-group">
                                                  <%= f.label :doa, "Date of Appointment", class: "bmd-label-floating"  %>
                                                  <%= f.text_field :doa, class: 'form-control change-to-white', id: "doa", placeholder: "Select date", data: {input: 'true'}%>
                                             </div>
                                        </div>
                                        <div class="row">
                                             <div class="col-md-4 form-group">
                                                  <%= f.label :job, class: "bmd-label-floating"  %>
                                                  <%= f.text_field :job, class: "form-control", style: "margin-top:5px;" %>
                                             </div>
                                             <div class="col-md-4 form-group">
                                                  <%= f.label :gender, class: "bmd-label-floating"  %>

                                                  <%=  f.select :gender, options_for_select(["Male", "Female"]), {prompt: "Selection Option"}, class: "form-control" %>
                                             </div>
                                             <div class="col-md-4 form-group">
                                                  <%= f.label :doctor, "Select you doctor", class: "bmd-label-floating"  %>
                                                  <%= f.collection_select :doctor_id, Doctor.order(:name), :id, :name,{prompt: "Select a doctor"}, {class: "form-control"}%>
                                             </div>
                                        </div>
                                        <div class="col-md-12">
                                             <center>
                                                  <%= f.submit "Submit Appointment", class: "btn btn-primary" %>
                                             </center>
                                        </div>
                                   <% end %>
                              </div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>


<script type="text/javascript">
    $('#datepicker_dob .input-group.date').datepicker({
        format: "yyyy-mm-dd",
        endDate: '+0d',
        autoClose: true

    });

    $('#datepicker_doa .input-group.date').datepicker({
        format: "yyyy-mm-dd",
        startDate: new Date()

    });
</script>

app/views/appointments/show.html.erb
<div class="offset-1 col-md-10">
     <div class="card">
          <div class="card-header card-header-primary">
               <h3 class="card-title">Thanks for your appointment</h3>
               <p class="card-category">Please review the details below</p>
          </div>
          <div class="card-body">
               <div class="row">
                    <div class="col-md-6">
                         <%= image_tag 'https://res.cloudinary.com/gibetirol/image/upload/c_scale,h_450/v1460370669/nueva_l2bvia.jpg' %>

                    </div>
                    <div class="col-md-6">
                         <p>
                              <h6>Name : </h6>
                              <h4><%= @appointment.name %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Address : </h6>
                              <h4><%= @appointment.address %></h4>
                              <hr />
                          </p>
                         <p>
                              <h6>Email : </h6>
                              <h4><%= @appointment.email %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Contact : </h6>
                              <h4><%= @appointment.contact %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Date of Birth : </h6>
                              <h4><%= @appointment.dob.strftime('%B %d, %Y')  %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Date of Appointment : </h6>
                              <h4><%= @appointment.doa.strftime('%B %d, %Y')  %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Job : </h6>
                              <h4><%= @appointment.job %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Doctor: </h6>
                              <h4><%= @appointment.doctor.name %></h4>
                              <hr />
                         </p>
                         <p>
                              <h6>Doctor: </h6>
                              <h4><%= @appointment.doctor.field.area %></h4>
                              <hr />
                         </p>
                         <p>
                              <%= link_to "Back to Appointment", all_appointments_path, class: "btn btn-primary" %>
                         </p>
                    </div>

               </div>
          </div>
     </div>
</div>

app/views/appointments/welcome.html.erb
<div class="container">
     <div class="row">
          <div class="col-sm-9 col-md-5 col-lg-5 mx-auto ">
               <div class="card card-signin my-5">
                    <div class="card-body">
                         <h6 class="card-title text-center">Welcome to Nueva Clinica</h6>
                         <center>
                              <%= image_tag("https://res.cloudinary.com/gibetirol/image/upload/c_scale,w_100/v1460370669/nueva_l2bvia.jpg", class: "text-center" , style: "margin-bottom: 30px;") %>
                         </center>
                         <%= link_to "Staff Login", login_path, class: "btn btn-info btn-block btn-lg", style: "border-radius: 100px !important;"  %>
                         <%= link_to "Doctor's Login",  doctor_login_path, class: "btn btn-primary btn-block btn-lg", style: "border-radius: 100px !important;" %>
                         <%= link_to "Fill-out for Doctor's Appointment", new_appointment_path, class: "btn btn-success btn-block btn-lg",style: "border-radius: 100px !important;"  %>
                         <%= link_to "View Doctors", list_doctors_path, class: "btn btn-warning btn-block btn-lg", style: "border-radius: 100px !important;"  %>
                    <p style="margin-top: 20px; text-align: center">
                         Contact Number: 0921 861 0943
                    </p>
                    </div>

               </div>
          </div>
     </div>
</div>